# Generated by Django 2.1.4 on 2018-12-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('start_accuracy', models.CharField(blank=True, max_length=10)),
                ('end_accuracy', models.CharField(blank=True, max_length=10)),
                ('is_momentary', models.BooleanField(blank=True, default=False)),
                ('url', models.URLField(blank=True)),
                ('affiliate', models.URLField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=3)),
                ('is_private', models.BooleanField(blank=True, default=False)),
                ('is_exclusive', models.BooleanField(blank=True, default=True)),
                ('wid', models.IntegerField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_quarks', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_quarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuarkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('name_prop', models.CharField(max_length=255)),
                ('start_prop', models.CharField(max_length=255)),
                ('end_prop', models.CharField(max_length=255)),
                ('has_gender', models.BooleanField(blank=True, default=False)),
                ('sort', models.IntegerField(max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quark',
            name='quark_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarks', to='graphql_api.QuarkType'),
        ),
    ]
