# Generated by Django 2.1.4 on 2018-12-14 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphql_api', '0004_auto_20181214_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gluon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.TextField(max_length=255)),
                ('prefix', models.TextField(blank=True, max_length=255)),
                ('suffix', models.TextField(blank=True, max_length=255)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('start_accuracy', models.CharField(blank=True, max_length=10)),
                ('end_accuracy', models.CharField(blank=True, max_length=10)),
                ('is_momentary', models.BooleanField(blank=True, default=False)),
                ('url', models.URLField(blank=True)),
                ('is_private', models.BooleanField(blank=True, default=False)),
                ('is_exclusive', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GluonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('caption_ja', models.CharField(max_length=255)),
                ('sort', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='quark',
            old_name='quark_type_id',
            new_name='quark_type',
        ),
        migrations.AddField(
            model_name='gluon',
            name='gluon_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gluons', to='graphql_api.GluonType'),
        ),
        migrations.AddField(
            model_name='gluon',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_gluons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gluon',
            name='object_quark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongings', to='graphql_api.Quark'),
        ),
        migrations.AddField(
            model_name='gluon',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_gluons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gluon',
            name='subject_quark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='havings', to='graphql_api.Quark'),
        ),
    ]
