# Generated by Django 2.1.4 on 2018-12-14 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0005_auto_20181214_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='QpropertyGtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gluon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_quark_properties', to='graphql_api.GluonType')),
            ],
        ),
        migrations.CreateModel(
            name='QpropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QtypeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarkProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('caption_ja', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='qtypeproperty',
            name='quark_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_quark_types', to='graphql_api.QuarkProperty'),
        ),
        migrations.AddField(
            model_name='qtypeproperty',
            name='quark_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='having_quark_properties', to='graphql_api.QuarkType'),
        ),
        migrations.AddField(
            model_name='qpropertytype',
            name='quark_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='having_quark_types', to='graphql_api.QuarkProperty'),
        ),
        migrations.AddField(
            model_name='qpropertytype',
            name='quark_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belonging_quark_properties', to='graphql_api.QuarkType'),
        ),
        migrations.AddField(
            model_name='qpropertygtype',
            name='quark_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='having_gluon_types', to='graphql_api.QuarkProperty'),
        ),
    ]
